### ISSUE TITLE
Integrate "website_id" in "List all Conversion"

### ISSUE THREAD

**Issue by Kinzi** [PerformanceHorizonGroup/apidocs#31]
Hey,

I'm not quite sure if this is the place to ask for this but I'll try:

Would it be possible for you to add the "website_id" key to the results from this query:
http://docs.performancehorizon.apiary.io/#reference/granular-publisher-reporting/conversions/list-all-conversions

Like:

```
"campaign_id": "10l176",
"publisher_id": "1l1007802",
"website_id": "10l176",
```

If not is there any request that features a publisher website identifier I could use to cross reference with the conversions list?

Thanks for your help!

Seb

**Comment by pete001** [comment]
Hi Seb, 

Unfortunately this isnt possible, as we dont have a direct correlation between the conversion that has been created with the website that was responsible for it (other than the `referer` url). 

The websites stored against a publisher are purely informational and intended for the advertiser who use these to understand where the traffic will predominantly come from. 

You could maintain a cache of `publisher_id` to an array of `website_id` and perform a look up on each `publisher_id` from the conversion listing. To get the websites:

If you are an advertiser: http://docs.performancehorizon.apiary.io/#reference/participating-publishers/participating-publishers/list-all-participating-publishers

If you are a publisher: http://docs.performancehorizon.apiary.io/#reference/publisher/publishers/list-publishers

**Comment by Kinzi** [comment]
Hey Pete,

thanks for getting back to me. Will look into it soon and report back. :)

**Comment by Kinzi** [comment]
Hey @pete001,

Just looked into it and I think it doesn't get me where I need to be. I would get an array of 'website_id' but still couldn't map a conversion to it's issuing website, only to all websites associated with this 'publisher_id'.

Also I don't have a referer url in my results from 
`https://private-anon-8f2ecb7859-performancehorizon.apiary-mock.com/reporting/report_publisher/publisher/publisher_id/conversion?`

My goal is to sort the conversions by their website id (or request them already filtered from the API).

Any other ideas? :)

**Comment by pete001** [comment]
Hey @Kinzi, 

Sorry for the delayed reply, i never got a notification this time round. 

Yeah there is no concrete reference to link a publisher's registered website to each conversion. The websites that a publisher creates, is purely informational, intended to be used by the advertiser to understand their predominant source of the traffic.

**Comment by pete001** [comment]
Closing after period of inactivity.
