### ISSUE TITLE
Conversion status is 'approved' not 'accepted'

### ISSUE THREAD

**Issue by Kinzi** [PerformanceHorizonGroup/apidocs#32]
Small bug: The correct value for key conversion_status should is 'approved' not 'accepted' (at least this is what I get back from the API) :)

http://docs.performancehorizon.apiary.io/#reference/granular-publisher-reporting/conversions/list-all-conversions

**Comment by pete001** [comment]
Ahh great find! Thanks for the issue @Kinzi, this is now patched and pushed up to apiary.
