### ISSUE TITLE
XML format

### ISSUE THREAD

**Issue by VeniceL** [PerformanceHorizonGroup/apidocs#58]
I'm not able to get the xml format to work - it was working in the past. The default json file is fine but adding .xml to the url is giving a 500 error.

**Comment by webmasterjunkie** [comment]
Hi @VeniceL,

Is there a specific API Endpoint you are experiencing this issue with?

Thanks!

**Comment by VeniceL** [comment]
Both of these 
api.performancehorizon.com/campaign.xml
api.performancehorizon.com/user/publisher/myid/campaign/a/tracking.xml

**Comment by webmasterjunkie** [comment]
Hi @VeniceL,

Appreciate the quick response! Could you please send an email through to the following support address:

support@partnerize.com

If you could provide your account name that you use to log into the Partnerize dashboard as well please. We will then be able to have a look at your issue through our support channel!

Thanks

**Comment by VeniceL** [comment]
Done. Thanks for responding so quickly.
Actually - I can edit my code to use the json format. But I thought you'd want to know that the xml format was giving an error.

**Comment by jb0o** [comment]
Thanks for raising this issue @VeniceL, I can see that you now have a support ticket in with us so I'll close this issue and you'll be updated on that support ticket directly.

Many thanks,
