### ISSUE TITLE
Add pubref to Publisher List All Conversions report

### ISSUE THREAD

**Issue by jllopezpino** [PerformanceHorizonGroup/apidocs#62]
It would be very useful for us publishers that you return the `pubref` associated to the conversion in this endpoint:
`https://api.performancehorizon.com/reporting/report_publisher/publisher/publisher_id/conversion
`
Documentation: https://performancehorizon.docs.apiary.io/#reference/granular-publisher-reporting/conversions/list-all-conversions

**Comment by jb0o** [comment]
Hi @jllopezpino!

Thanks for raising this request.

We'll be happy to look at exposing this however we need to assess this within our Product Team as a request.

I'll get this into our Product Feature Requests queue so keep posted in the future should we look to release this.

Many thanks,
JB
